# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidocs < Formula
  desc "Give your agents the power to publish reviewable HTML documents"
  homepage "https://github.com/anuragrao04/aidocs"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1/aidocs_0.0.1_darwin_amd64.tar.gz"
      sha256 "634659a57d394c3df17ad27a7c4139ceac559f337b84e811fad2736abe3132c5"

      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1/aidocs_0.0.1_darwin_arm64.tar.gz"
      sha256 "e31d6eccbf8073a19bdd39d6d07d71ce0895b90dbd682aab85617e9b7e168227"

      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1/aidocs_0.0.1_linux_amd64.tar.gz"
      sha256 "65c49c40ea2400ebc81bb921364cd73f8d46efb96614ecca0521c576441fee29"
      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1/aidocs_0.0.1_linux_arm64.tar.gz"
      sha256 "2dc324e2b76e601351c0db0d980a34beaea53b3c64aecd2e8ef7efa9b263230b"
      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
  end

  test do
    system "#{bin}/aidocs", "--help"
  end
end
