# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidocs < Formula
  desc "Give your agents the power to publish reviewable HTML documents"
  homepage "https://github.com/anuragrao04/aidocs"
  version "0.0.1-alpha.19"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.19/aidocs_0.0.1-alpha.19_darwin_amd64.tar.gz"
      sha256 "80ad1870ccc174bade608cc1d12f4a72f98a7c9303a8c089be0abe0665e217ae"

      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.19/aidocs_0.0.1-alpha.19_darwin_arm64.tar.gz"
      sha256 "7e4ce8518d4928657a88b75e71b89f2eeab579dc661f2666d1cb58b75598c743"

      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.19/aidocs_0.0.1-alpha.19_linux_amd64.tar.gz"
      sha256 "eb0cf8e8144841f201f6296b86cfe0234a02c59f8ceb5bbc93ed0d935bc7fdc2"
      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.19/aidocs_0.0.1-alpha.19_linux_arm64.tar.gz"
      sha256 "6b04056399aac42d56d29e4df3fff73568421a776351d918a39419bfb6727455"
      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
  end

  test do
    system "#{bin}/aidocs", "--help"
  end
end
