# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidocs < Formula
  desc "Give your agents the power to publish reviewable HTML documents"
  homepage "https://github.com/anuragrao04/aidocs"
  version "0.0.1-alpha.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.12/aidocs_0.0.1-alpha.12_darwin_amd64.tar.gz"
      sha256 "81acfbde62e9e2ca17a06e114b67792553138e42857b82bc1853885bb6511f71"

      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.12/aidocs_0.0.1-alpha.12_darwin_arm64.tar.gz"
      sha256 "eadf0c84eac9bcd367f33e6b085c4dda4dc418b584fd1526220e02b89fe4dbb5"

      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.12/aidocs_0.0.1-alpha.12_linux_amd64.tar.gz"
      sha256 "ed446ed29a810d92cf35e5abb7b6e8e243d217f3bdd18bde919608cd637fe28c"
      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anuragrao04/aidocs/releases/download/v0.0.1-alpha.12/aidocs_0.0.1-alpha.12_linux_arm64.tar.gz"
      sha256 "9539ac12eed0b84429f584adfa0318453757a34d266778a9924675e4f9ab6a9d"
      define_method(:install) do
        bin.install "aidocs"
        bash_completion.install "completions/aidocs.bash" => "aidocs"
        zsh_completion.install "completions/aidocs.zsh" => "_aidocs"
        fish_completion.install "completions/aidocs.fish"
      end
    end
  end

  test do
    system "#{bin}/aidocs", "--help"
  end
end
